# Exported from Render on 2024-03-18T16:04:03Z
services:
- type: web
  name: bp_test
  runtime: node
  repo: https://github.com/alexwbi88/express-test-prpreview
  branch: main
  plan: free
  disk: # Persistent disk configuration
    name: data
    mountPath: /data
    sizeGB: 10 # optional
version: "1"
