# Exported from Render on 2024-03-26T14:21:51Z
# services:
# - type: web
#   name: express-test-prpreview
#   runtime: node
#   repo: https://github.com/alexwbi88/express-test-prpreview
#   branch: main
#   plan: starter
#   envVars:
#   - key: .SECRETS
#     sync: false
#   - key: ENV
#     sync: false
#   - key: STRIPE_KEY
#     sync: false
#   - fromGroup: mygroup
#   region: oregon
#   buildCommand: yarn --frozen-lockfile install
#   startCommand: node app.js

databases:
- name: t_db
  databaseName: t4
  user: t4_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "13"

version: "1"
