# Exported from Render on 2024-03-18T16:04:03Z
previewsEnabled: true
services:
- type: web
  name: bp_test
  runtime: node
  repo: https://github.com/alexwbi88/express-test-prpreview
  branch: main
  plan: starter
  envVars:
  - key: ENV
    sync: false
  - key: STRIPE_API_KEY
    sync: false
  - fromGroup: mygroup
  region: oregon
  buildCommand: yarn && echo foo
  startCommand: node app.js
- type: web
  name: t5555
  runtime: node
  repo: https://github.com/render-examples/flask-hello-world
  branch: hello-spring
  plan: starter
  envVars:
  - key: STRIPE_API_KEY
    sync: false
  - key: ENV
    sync: false
  - fromGroup: mygroup
  region: oregon
  buildCommand: yarn && echo foo
  startCommand: node app.js
- type: web
  name: flask-hello-world
  runtime: python
  repo: https://github.com/render-examples/flask-hello-world
  branch: master
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
- type: redis
  name: t3
  plan: starter
  region: oregon
  maxmemoryPolicy: allkeys-lru
  ipAllowList: []
- type: web
    runtime: ruby
    name: sinatra-app
    repo: https://github.com/render-examples/sinatra # Default: Repo containing render.yaml
    numInstances: 3   # Manual scaling configuration. Default: 1 for new services
    region: frankfurt # Default: oregon
    plan: standard    # Default: starter
    branch: prod      # Default: master
    buildCommand: bundle install
    preDeployCommand: bundle exec ruby migrate.rb
    startCommand: bundle exec ruby main.rb
    autoDeploy: false # Disable automatic deploys
    maxShutdownDelaySeconds: 120 # Increase graceful shutdown period. Default: 30, Max: 300
    domains: # Custom domains
      - example.com
      - www.example.org
    envVars: # Environment variables
      - key: API_BASE_URL
        value: https://api.example.com # Hardcoded value
      - key: APP_SECRET
        generateValue: true # Generate a base64-encoded 256-bit value
      - key: STRIPE_API_KEY
        sync: false # Prompt for a value in the Render Dashboard
      - key: DATABASE_URL
        fromDatabase: # Reference a property of a database (see available properties below)
          name: mydatabase
          property: connectionString
      - key: MINIO_PASSWORD
        fromService: # Reference a value from another service
          name: minio
          type: pserv
          envVarKey: MINIO_ROOT_PASSWORD
      - fromGroup: my-env-group # Add all variables from an environment group
- type: web
    runtime: docker
    name: webdis
    repo: https://github.com/render-examples/webdis.git # Default: Repo containing render.yaml
    rootDir: webdis # Default: Repo root
    dockerCommand: ./webdis.sh # Default: Dockerfile CMD
    scaling: # Autoscaling configuration
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 60 # Optional if targetCPUPercent is set
      targetCPUPercent: 60    # Optional if targetMemory is set
    healthCheckPath: /
    registryCredential: # Default: No credential
      fromRegistryCreds:
        name: my-credentials
    envVars:
      - key: REDIS_HOST
        fromService: # Reference a property from another service (see available properties below)
          type: redis
          name: lightning
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: lightning
          property: port
      - fromGroup: conc-settings
- type: web
  name: t55
  runtime: python
  repo: https://github.com/alexwbi88/express-test-prpreview
  buildCommand: yarn && echo foo
  startCommand: node app.js
  numInstances: 3
  plan: standard
- type: web
  name: t556
  runtime: node
  repo: https://github.com/alexwbi88/express-test-prpreview
  buildCommand: yarn && echo foo
  startCommand: node app.js
  # numInstances: 3
  plan: starter
  autoDeploy: false # optional
  # maxShutdownDelaySeconds: 60 # seconds
  # disk:
  #   name: data
  #   mountPath: /data
  #   sizeGB: 10 # optional
  envVars:
    - key: STRIPE_API_KEY
      value: Z2V0IG91dHRhIGhlcmUhCg
    - key: ENV
      value: foo
    - fromGroup: mygroup
    - key: FILL_THIS_IN
      sync: false
    - fromGroup: conc-settings
    # - key: DB_URL
    #   fromDatabase:
    #     name: elephant
    #     property: connectionString
    # - key: DB_REPLICA_URL
    #   fromDatabase:
    #     name: elephant-replica
    #     property: connectionString
  scaling:
    minInstances: 1
    maxInstances: 3
    targetMemoryPercent: 60 # optional if targetCPUPercent is set
    targetCPUPercent: 60 # optional if targetMemory is set
  pullRequestPreviewsEnabled: true # optional
- type: web
  name: bp_test_new!
  runtime: node
  repo: https://github.com/alexwbi88/express-test-prpreview
  buildCommand: yarn
  startCommand: node app.js
  numInstances: 3
  plan: starter
  autoDeploy: false # optional
- type: redis
  name: lightning
  ipAllowList: # required
    - source: 0.0.0.0/0
      description: everywhere
  plan: free # optional (defaults to starter instance type)
  maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)
- type: pserv
  name: bp_test_private
  runtime: node
  repo: https://github.com/alexwbi88/express-test-prpreview
  scaling:
    minInstances: 1
    maxInstances: 3
    targetMemoryPercent: 60 # optional if targetCPUPercent is set
    targetCPUPercent: 60 # optional if targetMemory is set
  buildCommand: yarn
  startCommand: node app.js
  # plan: free
  autoDeploy: true # optional
- type: web
  name: bp_test2
  runtime: node
  repo: https://github.com/alexwbi88/express-test-prpreview
  # repo: https://github.com/alexwbi88/express-hello-world.git
  scaling:
    minInstances: 1
    maxInstances: 3
    targetMemoryPercent: 60 # optional if targetCPUPercent is set
    targetCPUPercent: 60 # optional if targetMemory is set
  buildCommand: yarn
  startCommand: node app.js
  plan: free
  autoDeploy: true # optional
  pullRequestPreviewsEnabled: true # optional
- type: web
  name: new_web_service_test
  runtime: node
  # repo: https://github.com/alexwbi88/express-hello-world
  # repo: https://github.com/alexwbi88/express-hello-world.git
  scaling:
    minInstances: 1
    maxInstances: 3
    targetMemoryPercent: 60 # optional if targetCPUPercent is set
    targetCPUPercent: 60 # optional if targetMemory is set
  buildCommand: yarn
  startCommand: node app.js
  autoDeploy: false # optional
 # A private service with an attached persistent disk
  - type: pserv
    runtime: docker
    name: minio
    repo: https://github.com/render-examples/minio.git # Default: Repo containing render.yaml
    envVars:
    - key: MINIO_ROOT_PASSWORD
      generateValue: true # Generate a base64-encoded 256-bit value
    - key: MINIO_ROOT_USER
      sync: false # Prompt for a value in the Render Dashboard
    - key: PORT
      value: 10000
    disk: # Persistent disk configuration
      name: data
      mountPath: /data
      sizeGB: 10 # optional

# A Python cron job that runs every hour
  - type: cron
    name: date
    runtime: python
    schedule: "0 * * * *"
    buildCommand: "true" # ensure it's a string
    startCommand: date
    repo: https://github.com/render-examples/docker.git # optional

# A Dockerfile-based background worker
  - type: worker
    name: queue
    runtime: docker
    dockerfilePath: ./sub/Dockerfile # Optional
    dockerContext: ./sub/src # Optional
    branch: queue # Optional

# A static site
  - type: web
    name: my-blog
    runtime: static
    buildCommand: yarn build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true # Enable service previews
    buildFilter:
      paths:
      - src/**/*.js
      ignoredPaths:
      - src/**/*.test.js
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /old
        destination: /new
      - type: rewrite
        source: /a/*
        destination: /a

# A Redis instance
  - type: redis
    name: lightning
    ipAllowList: # Required
      - source: 0.0.0.0/0
        description: everywhere
    plan: free # Default: starter
    maxmemoryPolicy: noeviction # Default: allkeys-lru

# List all PostgreSQL databases here
databases:
  # A database with a read replica
  - name: elephant
    databaseName: mydb # Optional (Render may add a suffix)
    user: adrian # Optional
    ipAllowList: # Optional (defaults to allow all)
      - source: 203.0.113.4/30
        description: office
      - source: 198.51.100.1
        description: home
    readReplicas:
      - name: elephant-replica

  # A database that allows only private network connections
  - name: private database
    databaseName: private
    ipAllowList: [] # No entries in the IP allow list

  # A database that enables high availability
  - name: highly available database
    plan: pro
    highAvailability:
      enabled: true

envVarGroups:
  - name: conc-settings
    envVars:
      - key: CONCURRENCY
        value: 2
      - key: SECRET
        generateValue: true
      - key: USER_PROVIDED_SECRET
        sync: false
  - name: stripe
    envVars:
      - key: STRIPE_API_URL
        value: https://api.stripe.com/v2
  - name: mygroup
    envVars:
      - key: REALLY_SECRET_KEY
        # value: abc123
        sync: false
      - key: THISONEISFINE
        # value: def456
        sync: false

version: "1"
