# Exported from Render on 2024-03-18T16:04:03Z
services:
- type: web
  name: bp_test
  runtime: node
  repo: https://github.com/alexwbi88/express-test-prpreview
  branch: main
  plan: free
  envVars:
  - key: ENV
    sync: false
  - key: STRIPE_API_KEY
    sync: false
  - fromGroup: mygroup
  region: oregon
  buildCommand: yarn && echo foo
  startCommand: node app.js
  preDeployCommand: bundle exec ruby migrate.rb
version: "1"
