previewsEnabled: true
services:
-   type: web
    name: bp_test
    runtime: node
    repo: https://github.com/alexwbi88/express-test-prpreview
    buildCommand: yarn
    startCommand: node app.js
    numInstances: 3
    plan: starter
    autoDeploy: true # optional
    envVars:
      - key: STRIPE_API_KEY
        value: Z2V0IG91dHRhIGhlcmUhCg
      - key: DB_URL
        fromDatabase:
          name: elephant
          property: connectionString
      - key: DB_REPLICA_URL
        fromDatabase:
          name: elephant-replica
          property: connectionString
    # scaling:
    #   minInstances: 1
    #   maxInstances: 3
    #   targetMemoryPercent: 60 # optional if targetCPUPercent is set
    #   targetCPUPercent: 60 # optional if targetMemory is set
    # pullRequestPreviewsEnabled: true # optional
# -   type: redis
#     name: lightning
#     ipAllowList: # required
#       - source: 0.0.0.0/0
#         description: everywhere
#     plan: free # optional (defaults to starter instance type)
#     maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)
# -   type: pserv
#     name: bp_test_private
#     runtime: node
#     # repo: https://github.com/alexwbi88/express-hello-world.git
#     # scaling:
#       # minInstances: 1
#       # maxInstances: 3
#       # targetMemoryPercent: 60 # optional if targetCPUPercent is set
#       # targetCPUPercent: 60 # optional if targetMemory is set
#     buildCommand: yarn
#     startCommand: node app.js
#     plan: free
#     autoDeploy: true # optional
# -   type: web
#     name: bp_test2
#     runtime: node
#     repo: https://github.com/alexwbi88/express-test-prpreview
#     # repo: https://github.com/alexwbi88/express-hello-world.git
#     # scaling:
#       # minInstances: 1
#       # maxInstances: 3
#       # targetMemoryPercent: 60 # optional if targetCPUPercent is set
#       # targetCPUPercent: 60 # optional if targetMemory is set
#     buildCommand: yarn
#     startCommand: node app.js
#     plan: free
#     autoDeploy: true # optional
#     pullRequestPreviewsEnabled: true # optional
# -   type: web
#     name: new_web_service_test
#     runtime: node
#     repo: https://github.com/alexwbi88/express-hello-world
#     # repo: https://github.com/alexwbi88/express-hello-world.git
#     # scaling:
#       # minInstances: 1
#       # maxInstances: 3
#       # targetMemoryPercent: 60 # optional if targetCPUPercent is set
#       # targetCPUPercent: 60 # optional if targetMemory is set
#     buildCommand: yarn
#     startCommand: node app.js
#     autoDeploy: false # optional
