# Exported from Render on 2024-03-26T14:18:18Z
services:
- type: web
  name: express-test-prpreview
  runtime: node
  repo: https://github.com/alexwbi88/express-test-prpreview
  branch: main
  plan: starter
  region: oregon
  buildCommand: yarn --frozen-lockfile install
  startCommand: node app.js
version: "1"
